import BottomSection from "@/modules/bottomsection";
import TopSection from "@/modules/top-section";
import { wrapper } from "@/store/store";
import { InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { getResults } from "./api/hello";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    const results = await store.dispatch(
      getResults.initiate({
        searchValue: store.getState().search.searchValue,
        page: store.getState().viewMode.page,
        itemsPerPage: store.getState().viewMode.itemsPerPage,
      })
    );

    return {
      props: {
        products: results.data,
      },
    };
  }
);

export default function Home({
  products,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>React Wars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="main">
        <header className="header">
          <h1 className="header__header">
            <s>StarWars Ships</s> Some crap
          </h1>
        </header>
        <TopSection></TopSection>
        <BottomSection {...products}></BottomSection>
      </main>
    </>
  );
}
