import TopSection from "@/modules/top-section";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>React Wars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="main">
        <header className="header">
          <h1 className="header__header">
            <s>StarWars Ships</s> Some crap
          </h1>
        </header>
        <TopSection></TopSection>
      </main>
    </>
  );
}
